In [33]:
import torch

def complete_bipartite_edges(m,n,prob):
    row = torch.arange(m).reshape(-1,1).tile(n).reshape(-1)
    col = torch.arange(n).repeat(m)
    n = int(prob * len(row))
    indices = list(zip(row, col))
    random_pairs = random.sample(indices, n)
    random_pairs = torch.tensor(np.array(random_pairs)).T
    return random_pairs

complete_bipartite_edges(10,10, 0.1)

tensor([[9, 0, 3, 4, 5, 2, 8, 8, 3, 2],
        [7, 9, 6, 3, 3, 1, 1, 7, 3, 3]])

In [26]:
import numpy as np
m = 3
n = 4
row = torch.arange(m).reshape(-1,1).tile(n).reshape(-1)
col = torch.arange(n).repeat(m)

In [29]:
# Combine x and y coordinates into pairs of indices


# Number of random pairs to sample
n_samples = 5

# Randomly sample pairs of indices
random_pairs = random.sample(indices, n_samples)

# Separate the sampled pairs back into x and y coordinates
sampled_x_coordinates, sampled_y_coordinates = zip(*random_pairs)

print("Sampled x coordinates:", sampled_x_coordinates)
print("Sampled y coordinates:", sampled_y_coordinates)


Sampled x coordinates: (tensor(0), tensor(1), tensor(1), tensor(2), tensor(0))
Sampled y coordinates: (tensor(0), tensor(2), tensor(1), tensor(3), tensor(1))


In [32]:

# Convert the list of pairs to a NumPy array
pairs_array = np.array(random_pairs)

# Convert the NumPy array to a PyTorch tensor
tensor = torch.tensor(pairs_array)
tensor.T

tensor([[0, 1, 1, 2, 0],
        [0, 2, 1, 3, 1]])

In [25]:
import random

# Create a list of points (each point is represented as a list)
points = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]

# Number of random points to sample
x = 3

# Randomly sample x points from the list
randomly_sampled_points = random.sample(points, x)

print(randomly_sampled_points)


[[3, 4], [9, 10], [5, 6]]


In [24]:
import random
random.choice(list(torch.stack([row, col]).T), 5)

TypeError: Random.choice() takes 2 positional arguments but 3 were given

In [23]:
list(torch.stack([row, col]).T)

[tensor([0, 0]),
 tensor([0, 1]),
 tensor([0, 2]),
 tensor([0, 3]),
 tensor([1, 0]),
 tensor([1, 1]),
 tensor([1, 2]),
 tensor([1, 3]),
 tensor([2, 0]),
 tensor([2, 1]),
 tensor([2, 2]),
 tensor([2, 3])]

In [8]:
x_coordinates[1]

tensor(0)

In [5]:
import torch
import random

# Create tensors for x and y coordinates
x_coordinates = torch.tensor([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2])
y_coordinates = torch.tensor([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3])

# Combine x and y coordinates into pairs of indices
indices = list(zip(x_coordinates, y_coordinates))

# Number of random pairs to sample
n_samples = 5

# Randomly sample pairs of indices
random_pairs = random.sample(indices, n_samples)

# Separate the sampled pairs back into x and y coordinates
sampled_x_coordinates, sampled_y_coordinates = zip(*random_pairs)

print("Sampled x coordinates:", sampled_x_coordinates)
print("Sampled y coordinates:", sampled_y_coordinates)


Sampled x coordinates: (tensor(0), tensor(2), tensor(1), tensor(1), tensor(0))
Sampled y coordinates: (tensor(0), tensor(3), tensor(1), tensor(2), tensor(2))
